sudo: false
language: python
addons:
  postgresql: 10.4
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
    - postgresql-server-dev-10
    - postgresql-contrib
python:
  - 3.6
env:
  global:
    - URSH_CONFIG=/dev/null
install:
  - pip install flake8
  - pip install isort
  - pip install -e .
script:
  - flake8 .
  - isort --check-only --diff --quiet
  - pytest -rs -v
notifications:
  email: false
